<?php
include("head.php");
include("header.php");
include("connect.php");
include("stats.php");
include("bestsellers.php");
include("testimonials.php");
include("contactus.php");
include("footer.php");
