<?php
include("head.php");
include("header.php");
include("connect.php");
include("stats.php");
include("bestSellers.php");
include("testimonials.php");
include("contactUs.php");
include("footer.php");
